name: Build & Deploy Busybox RPMs

on:
  push:
    branches:
      - 7.2-beta
    tags:
      - "*"
  pull_request:
    branches:
      - 7.2-beta
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: fedora:42

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf clean all && dnf makecache
          dnf install -y rpm-build rpmdevtools createrepo_c
          dnf install -y libv4l-devel
          dnf install -y 'dnf-command(builddep)'

      - name: Set up RPM build environment
        run: |
          rpmdev-setuptree

      - name: Download Fedora's Busybox Source RPM
        run: |
          dnf download --source busybox
          rpm -ivh busybox-*.src.rpm

      - name: Apply patches to spec file (if any)
        run: |
          cd ~/rpmbuild/SPECS
          if compgen -G "$GITHUB_WORKSPACE/patches/SPECS/*.patch" > /dev/null; then
            cp $GITHUB_WORKSPACE/patches/SPECS/*.patch .
            for patch in *.patch; do
              patch -p1 < "$patch"
            done
          fi

      - name: Install Build Dependencies
        run: |
          dnf builddep -y ~/rpmbuild/SPECS/busybox.spec

      - name: Build the RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/busybox.spec

      - name: Prepare RPM Repository
        run: |
          mkdir -p repo
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -exec cp {} repo/ \;
          createrepo_c repo/

      - name: Upload RPMs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: busybox
          path: repo/

  deploy:
    needs: build-rpm
    runs-on: ubuntu-latest
    if: always()
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Built RPMs
        uses: actions/download-artifact@v4
        with:
          name: busybox
          path: temp-repo/

      - name: Move RPMs to Versioned Subdirectory
        run: |
          mkdir -p publish/7.2/x86_64
          cp -r temp-repo/* publish/7.2/x86_64/

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
